// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameStore.Data;

#nullable disable

namespace Fulfillment.Data.Migrations
{
    [DbContext(typeof(VideoGameStoreDbContext))]
    partial class VideoGameStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameStore.Data.Entities.Buying", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Stauts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Buyings");
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.BuyingLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyingId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyingId")
                        .IsUnique();

                    b.ToTable("BuyingLines");
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lyon.kennedy@gmail.com",
                            Name = "Lyon Kennedy"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lara.croft@gmail.com",
                            Name = "Lara Croft"
                        },
                        new
                        {
                            Id = 3,
                            Email = "fox.mccloud@gmail.com",
                            Name = "Fox McCloud"
                        });
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.FulfillmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FulfilledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FulfillmentEvents");
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStock = 5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentStock = 3,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            CurrentStock = 9,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CurrentStock = 7,
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.Videogame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ESRB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SpeIden")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SpeIden")
                        .IsUnique();

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ESRB = "E for Everyone",
                            Name = "Donkey Kong Bananza",
                            Price = 78.50m,
                            SpeIden = "VGM-001"
                        },
                        new
                        {
                            Id = 2,
                            ESRB = "+13 years old",
                            Name = "Halo Remaster Collection",
                            Price = 48.90m,
                            SpeIden = "VGM-002"
                        },
                        new
                        {
                            Id = 3,
                            ESRB = "E for Everyone",
                            Name = "Minecraft",
                            Price = 22.75m,
                            SpeIden = "VGM-003"
                        },
                        new
                        {
                            Id = 4,
                            ESRB = "E+10",
                            Name = "Terraria",
                            Price = 15.50m,
                            SpeIden = "VGM-004"
                        });
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.Buying", b =>
                {
                    b.HasOne("VideoGameStore.Data.Entities.Customer", "Customer")
                        .WithMany("buyings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.BuyingLine", b =>
                {
                    b.HasOne("VideoGameStore.Data.Entities.Buying", null)
                        .WithOne("Lines")
                        .HasForeignKey("VideoGameStore.Data.Entities.BuyingLine", "BuyingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("VideoGameStore.Data.Entities.Videogame", "Videogame")
                        .WithOne("Inventory")
                        .HasForeignKey("VideoGameStore.Data.Entities.InventoryItem", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.Buying", b =>
                {
                    b.Navigation("Lines")
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.Customer", b =>
                {
                    b.Navigation("buyings");
                });

            modelBuilder.Entity("VideoGameStore.Data.Entities.Videogame", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
